### ISSUE TITLE
SCH has points in Lnum

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#11]
This seemed to be a non issue, but the file generating babylon gives duplicate of 1 for 1.1 Lnum.

**Comment by funderburkjim** [comment]
The display for SCH  is not showing all the information of the xml.  Here is example for hw = 'a'

![image](https://user-images.githubusercontent.com/6393033/51652496-de174f80-1f5d-11e9-9f62-3b2fe5a20654.png)

display:

![image](https://user-images.githubusercontent.com/6393033/51652524-f38c7980-1f5d-11e9-9c48-a7aa683c2f59.png)

digitization (sch.txt):
```
<L>1<pc>001-1<k1>a<k2>a°
{#a#} {%a°%}¦ {!2!}  , {%asvaptum%} Tāṇḍya-Br. 10 , 4 , 4. {part=,seq=1,type=,n=1}
<LEND>
<L>1.1<pc>001-1<k1>a<k2>a
{#a#} {%a%}¦ {!4!}  m. º= {%sarvajño 'rhan%} , S I , 53 , 3. — Viṣṇu , H 31 , 9; Vās. 113 , 1. 
{part=,seq=2,type=*,n=2}
<LEND>
```

data from sch.xml:
```
<H1><h><key1>a</key1><key2>a°</key2></h><body><hom n="pwk">2</hom>  , 
<i>asvaptum</i> Tāṇḍya-Br. 10 , 4 , 4. </body><tail><info seq="1" n="1"/>
<L>1</L><pc>001-1</pc></tail></H1>

<H1><h><key1>a</key1><key2>a</key2></h><body><hom n="pwk">4</hom>  
m. º= <i>sarvajño 'rhan</i> , S I , 53 , 3. <div>— Viṣṇu , H 31 , 9; Vās. 113 , 1. </div>
<type>*</type></body><tail><info seq="2" n="2"/>
<L>1.1</L><pc>001-1</pc></tail></H1>
```

There is useful information in
a)  the pwk homonym number
b)  the '*' (though I forget the significance, it does have some significance mentioned in the front matter for sch.)

It would be better for the Cologne display to show this information.
Also better for the stardict version to also show.

**Comment by gasyoun** [comment]
> b) the '*' (though I forget the significance, it does have some significance mentioned in the front matter for sch.)

As one can read at https://github.com/sanskrit-lexicon/SCH/blob/master/SCH-Nachtraege.pdf in German

`Die im pw ganz fehlenden Wörter resp. Bedeutungen oder ein solches Genus habe ich wieder wie bisher mit ° bezeichnet, während * besagt, daß das Betreffende daselbst noch nicht belegt ist.`

° - words / or meaning / or gender (it stands right before the new addition) added in SCH, missing totally in PWK
* - means a hypothethical form, that SCH supposes should exist, but can't proove, so it's a reconstruction

**Comment by drdhaval2785** [comment]
This seems to be a non issue nowadays. Closing this issue.
