### ISSUE TITLE
remove lxml dependency of make_babylon.py

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#18]
Native etree should be sufficient.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/cologne-stardict/commit/e0399fefa3a8bb5b6f226a07750d2de69c7617f1

**Comment by funderburkjim** [comment]
Good idea.  lxml is more convenient, but harder to install, at least on Windows.  So good to use etree which is built in to Python.

In xmlvalidate.py,  lxml was required, since etree did not support xml validation.
