### ISSUE TITLE
Make babylons from txt instead of XML

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#20]
Current implementation of make_babylon.py used xxx.xml file as input file. This has some programmatic problems.
1. It requires generation of XML locally.
2. make_babylon.py is a python2 only program. Will need to make it python3 compatible.
3. It is very unwieldy program. Essentially it was made up of lots of patches to take different idiosyncracies into account.
4. Jim completed metaline and IAST conversion. So majority of metadata required is already available in txt file itself.
5. etree module freezes my computer when trying to parse large xml files such as pwg.xml. 

Therefore,  a rehaul of codebase is required.

**Comment by funderburkjim** [comment]
We may need to be aware of markup assumptions made by programs that generate 'babylons' from xxx.txt files.  For just one example, if we remove line-break markup from xxx.txt,  we need to be sure the make_babylon.py program still works properly.  

Currently, we have to coordinate between xxx.txt markup and make_xml.py.
Similar coordination needed between xxx.txt markup and make_babylon.py.

**Comment by gasyoun** [comment]
> programs that generate 'babylons'

Wonder if people still us 'em.

**Comment by vvasuki** [comment]
> > programs that generate 'babylons'
> 
> Wonder if people still us 'em.

I know they do - https://github.com/sanskrit-coders/stardict-dictionary-updater/issues/34 . Looks like atleast about 10 russkies do as well.

**Comment by drdhaval2785** [comment]
The only reason to use babylon is to generate stardict files. Stardict readers are super fast. EBDic viewer which I use gives me results from around 50+ dictionaries in a few milliseconds, almost instantaneously.

**Comment by gasyoun** [comment]
> about 10 russkies do as well

Oh, in that case it should continue ))

> Stardict readers are super fast

Strong argument indeed.

**Comment by funderburkjim** [comment]
Supposedly, Windows 11 will support Android apps.

Thus, it might be possible to use the stardict dictionary versions also in future Windows versions.

**Comment by gasyoun** [comment]
> Windows 11

As if Windows 10 was not bad enough ))

**Comment by drdhaval2785** [comment]
From commit https://github.com/sanskrit-lexicon/cologne-stardict/commit/cd134f16172b45b7730003cfb1854d99765da360 now onwards, make_babylon.py uses csl-orig/v02/xxx.txt file directly.
