### ISSUE TITLE
hwextra to be roped in

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#21]
While generating acc.babylon from acc.txt, the following error was observed.
The alternative word aNkArohaRaprayoga is removed from babylon file.

```
अङ्कारोहण
अङ्कारोहण and अङ्कारोहणप्रयोग dh. Burnell 151^a.

[-अङ्कारोहणप्रयोग-]
[-अङ्कारोहणप्रयोग is an alternate of अङ्कारोहण. अङ्कारोहण and अङ्कारोहणप्रयोग dh. Burnel
```

The reason is that XML has some hack by which it fetches the data from acc_hwextra.txt and creates an entry for the alternate headword.
This hwextra file has to be handled in babylon regeneration, so that information is not missed.

Good thing about babylon is that order is not important. Therefore, we can append the hwextra data after the main entries get over.

**Comment by drdhaval2785** [comment]
It seems that alternate headword issue is handled now.
I am not sure about embedded entries yet.
Closing this issue.

**Comment by gasyoun** [comment]
> It seems that alternate headword issue is handled now.

It's lost or integrated?

**Comment by drdhaval2785** [comment]
Integrated.
