### ISSUE TITLE
breaching 100 MB threshold in mw.babylon

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#31]
As the mw.babylon file with links to pdf and source text exceeded 100 MB threshold of github, I ran into some problem.
This issue is directed to explore the possibility of git-lfs (git large file storage) feature to see if I can overcome this issue.

**Comment by vvasuki** [comment]
URL shorteners?

branching out sa-en dicts into a separate repo?

**Comment by drdhaval2785** [comment]
I think, it would not be much of an issue. 
We had been already receiving 'Warnings'. It is now giving 'Errors'. 
Some day we need to learn new tools. Time is ripe for 'git lfs'.
If I fail in this endeavour, we can fall back to ideas suggested by you.

**Comment by drdhaval2785** [comment]
# Steps

1. Download latest git-lfs tar.gz. `wget --content-disposition https://packagecloud.io/github/git-lfs/packages/ubuntu/bionic/git-lfs_3.0.1_amd64.deb/download.deb`
2. Install the package. `sudo gdebi git-lfs_3.0.1_amd64.deb`
3. Track the file you want to handle via 'git lfs'. In the present case it was `git lfs track production/mw.babylon`
4. This writes some information to .gitattributes file which tells git to handle this particular file via 'git lfs'. Check the content via `cat .gitattributes`
5. Add the .gitattributes file. `git add .gitattributes`
6. `git commit -m 'add .gitattribues'`
7. `git push`
8. Add the file production/mw.babylon . `git add production/mw.babylon`
9. `git commit -m 'test'`
10. `git push`

This uploaded the file without any complaints.

**Comment by funderburkjim** [comment]
Question:  Various of the '.babylon' files use the 'lfs' storage (e.g. [skd.babylon](https://github.com/sanskrit-lexicon/cologne-stardict/blob/master/output/skd.babylon)).

But none of these files shows as 100MB+.  So why was lfs required?

**Comment by drdhaval2785** [comment]
They were in 'Warning' stage i.e. between 50 to 100 MB. Git was giving suggestion to use LFS. So stored them in LFS, to silence the warnings.
