### ISSUE TITLE
Give Devanagari to interested people to correct

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#32]
Ref - https://github.com/indic-dict/stardict-sanskrit/issues/122#issuecomment-933370253

@vvasuki wanted to have Devanagari text for proof reading.
Different people may have different preferences towards various transliteration schemes.

I am also pro-Devanagari.

Would it be wise to get a Devanagari version, maybe only for 100% Devanagari lexica such as KRM, SKD, VCP, ARMH ?
I would lean towards such an implementation.

What is your take @funderburkjim ?

**Comment by funderburkjim** [comment]
slp1 can be converted to Devanagari, and vice-versa -  and this in a lossless way.
In fact, I thought that getting a Devanagari version was your objective in the csl-devanagari repository.

So, isn't a `Devanagari version` already a fait accompli?

**Comment by drdhaval2785** [comment]
Yes. Devanagari is generated in lossless manner. 
It is matter of creating csl-lnum like thing in Devanagari, so that individual entry can be edited directly.

**Comment by gasyoun** [comment]
> I am also pro-Devanagari.

Yes, as all Indians are. They find it easier. So why to go against it?

**Comment by Andhrabharati** [comment]
> slp1 can be converted to Devanagari, and vice-versa - and this in a lossless way.

I guess, one might not doubt this.

**But the reverse (Devanagari-slp1-Devanagari) is not always lossless!**

One such occassion has come up recently, when I've pointed a conversion error in PWG to Dhaval (through personal mail).

Just thought I should post the info here, as "lossless" reversibility is thought of "the strong reason" of having the CDSL texts in slp1 encoding;  details may be shared by Dhaval, if he feels it important enough.

**Comment by drdhaval2785** [comment]
With the advent of csl-ldev and csl-devanagari repositories, this issue is now resolved.
