### ISSUE TITLE
Remove git lfs and shorten URLs

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#33]
git lfs caused a lot of trouble or downstream applications like csl-json.
Removed git lfs support for rest of the dictionaries.

MW is a tricky issue.
It is more than 100 MB. Therefore github will not accept it.
I need to shorten URLs for scanned page and correction page to bring it below 100 MB, so that business can continue as usual.

**Comment by gasyoun** [comment]
> I need to shorten URLs for scanned page

By replacing ... to ... ?

**Comment by drdhaval2785** [comment]
Removed git lfs.
For MW, just removed the correction submission link.

**Comment by vvasuki** [comment]
Reopen please. Try this solution 

- https://yaahi.github.io/?mw=2.txt redirects to https://github.com/sanskrit-lexicon/csl-ldev/blob/main/v02/mw/2.txt
- https://yaahi.github.io/?cp=0001-a&d=MW72 redirects to https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW72&page=0001-a

**Comment by gasyoun** [comment]
> https://yaahi.github.io/?cp=0001-a&d=MW72 redirects to https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW72&page=0001-a

Makes sense @drdhaval2785 ?

**Comment by drdhaval2785** [comment]
Yes it does. Looks a bit creepy, but works.

**Comment by drdhaval2785** [comment]
> https://yaahi.github.io/?mw=2.txt 

We would need something like https://yaahi.github.io/?skd=2.txt also to work.

**Comment by drdhaval2785** [comment]
> https://yaahi.github.io/?mw=2.txt 

We need to keep it working across dictionaries, just as the scan page links.
https://yaahi.github.io/?d=mw&e=2
dictionaray = mw
entry = 2

**Comment by vvasuki** [comment]
Done

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/cologne-stardict/commit/bb8928c4f0fb1a1bd80db2e467129ceee985c324 onwards to aebe16ed4abb2216aea17b327372b3dfd57af86a correct this.
Now the links are short as shown in comments above.

**Comment by drdhaval2785** [comment]
MW is 71 MB. So, now every dictionary is below 100 MB threshold.
