### ISSUE TITLE
Bad headword पर्ॐहु

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-lexicon/cologne-stardict#35]
```
पर्ॐहु
पर्ॐहु परो-ऽंहु। See under परस्।<BR><a href="https://yaahi.github.io/?cp=0552-c&d=MW72" target="_blank">PDF</a><BR><a href="https://yaahi.github.io/?d=mw72&e=28286" target="_blank">Correction</a>
```

- Tangentially reminiscent of https://github.com/sanskrit-lexicon/LRV/issues/6#issuecomment-1254320502 
- Noticed thanks to https://github.com/sanskrit-lexicon/MWS/issues/141#issuecomment-1254753999

**Comment by gasyoun** [comment]
@funderburkjim or @drdhaval2785 issue?

**Comment by drdhaval2785** [comment]
I think this issue is handled now.
Closing this issue.
Can reopen if need be.
