### ISSUE TITLE
MW has multiple headword types

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/cologne-stardict#6]
Other dictionaries mostly have `H1` only.
MW has a lot more headword types like H1B, H2, H3 etc.

**Comment by drdhaval2785** [comment]
Four and no more @gasyuon and @funderburkjim?

**Comment by funderburkjim** [comment]
MW has 4 headword types (H1 ... H4);   this is the digitization's way of distinguishing the '4 lines' of Sanskrit words that MW preface describes.
the 'ABCE' suffixes are also used.  This is purely an artifice of the Cologne digitization.  Main purpose is to distinguish the different senses and genders under nominals.

For the other dictionaries, there is (I think) only H1.   This was done purely to  make the xml forms of the other dictionaries similar to that of MW.

**Comment by gasyoun** [comment]
> This was done purely to make the xml forms of the other dictionaries similar to that of MW.

Oh, missed that.

**Comment by drdhaval2785** [comment]
Nothing remains to be done.
